import PolicyPage from "../components/PolicyPage";
export default function AffiliateDisclosure() { return <PolicyPage title="Affiliate Disclosure" description="How optional affiliate campaigns, tracking, commissions and related X-Coin offers work." path="/affiliate-disclosure" sections={[
  { title: "Our affiliate relationship", content: <p>Future-X may show clearly identified links or campaigns for products and services supplied by independent third parties. If you complete an eligible action or purchase through one of these links, Future-X may receive a commission or other benefit.</p> },
  { title: "Optional participation", content: <p>Affiliate campaigns are optional. You do not need to click or buy an offer to use core Future-X features. Do not purchase something solely because an X-Coin offer is displayed. Consider the product’s usefulness, total cost and terms independently.</p> },
  { title: "Prices and editorial independence", content: <p>A commission does not permit Future-X to control a provider’s pricing. Offers, rankings or descriptions may be influenced by commercial relationships and will be labelled where appropriate. A listing is not a guarantee, endorsement or professional recommendation.</p> },
  { title: "Third-party responsibility", content: <p>The provider—not Future-X—controls product descriptions, eligibility, inventory, billing, recurring charges, fulfilment, privacy, warranties, cancellations, returns and support. Verify the provider’s identity and review all terms before continuing.</p> },
  { title: "Tracking and reward verification", content: <p>Affiliate links may include campaign and attribution identifiers. The provider or affiliate network may report whether an eligible action occurred so Future-X can calculate commission and, where offered, verify X-Coin eligibility. Tracking can fail or be delayed, and opening a link or making a purchase does not guarantee X-Coins.</p> },
  { title: "Cancellations, returns and abuse", content: <p>If an order is cancelled, returned, refunded, duplicated, fraudulent or otherwise disqualified, related X-Coins may be withheld or reversed. Manipulating links, attribution, devices, identities or transactions is prohibited.</p> },
  { title: "Questions or concerns", content: <p>Contact the provider first for product, billing, return or delivery issues. Report a misleading or unsafe campaign to <a href="mailto:admin@future-x.co.in?subject=Affiliate%20Campaign%20Report">admin@future-x.co.in</a>.</p> },
]} />; }
