import PolicyPage from "../components/PolicyPage";
export default function CommunityGuidelines() { return <PolicyPage title="Community Guidelines" description="Standards for safe content, respectful conduct and fair participation on Future-X." path="/community-guidelines" sections={[
  { title: "Be respectful and safe", content: <p>Do not harass, threaten, bully, discriminate against, sexually exploit, impersonate or deceive another person. Do not reveal another person’s private information without permission or encourage dangerous conduct.</p> },
  { title: "Content standards", content: <p>If reels, profiles or other features allow submissions or interaction, do not upload illegal, hateful, sexually explicit or exploitative, graphically violent, fraudulent, harmful or rights-infringing content. Do not promote scams, illegal goods or misleading earning claims.</p> },
  { title: "Participate honestly", content: <p>Use one genuine account, provide accurate eligibility information and complete activities yourself. Bots, scripts, emulators, collusion, artificial views or ad interactions, manipulated spins, fabricated task completion and exploitation of errors are prohibited.</p> },
  { title: "Protect accounts and the platform", content: <p>Never request or share passwords or OTPs. Do not distribute malware, probe security, bypass controls, alter the app, interfere with Firebase or reward records, overload services or attempt unauthorised access.</p> },
  { title: "Moderation and enforcement", content: <p>Future-X may use automated signals and human review to investigate reports. Depending on severity and context, we may reduce visibility, remove content, reverse ineligible X-Coins, limit features, reject redemptions, suspend or close accounts, preserve evidence or notify relevant authorities.</p> },
  { title: "Reporting and review", content: <p>Report the account or content identifier, activity, date and non-sensitive evidence to <a href="mailto:admin@future-x.co.in?subject=Safety%20Report">admin@future-x.co.in</a>. Do not share sensitive evidence publicly. Affected users may contact support to request review of an enforcement decision.</p> },
]} />; }
