import { useState } from "react";
import type { FormEvent } from "react";
import { Clock, Mail, MapPin, Send } from "lucide-react";
import Seo from "../components/Seo";

export default function Contact() {
  const [status, setStatus] = useState("");
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); if (data.get("website")) return; const subject = encodeURIComponent(`[Future-X] ${String(data.get("subject"))}`); const body = encodeURIComponent(`Name: ${String(data.get("name"))}\nReply email: ${String(data.get("email"))}\n\n${String(data.get("message"))}`); setStatus("Your email app is opening. Please send the prepared message to complete your request."); window.location.href = `mailto:admin@future-x.co.in?subject=${subject}&body=${body}`; }
  return <main id="main-content" className="page-main"><Seo title="Contact Future-X" description="Contact the Future-X team for support, business, affiliate and privacy enquiries." path="/contact" /><header className="page-hero compact"><div className="container narrow"><span className="eyebrow">Contact</span><h1>How can we help?</h1><p>Send a clear description and any relevant account or activity reference. Never send passwords or one-time codes.</p></div></header><section className="section container contact-grid"><div className="contact-details"><h2>Contact details</h2><a href="mailto:admin@future-x.co.in"><Mail /> <span><strong>Email</strong>admin@future-x.co.in</span></a><div><MapPin /><span><strong>Business location</strong>Mathura, Uttar Pradesh, India</span></div><div><Clock /><span><strong>Support hours</strong>Monday–Saturday, 10:00–18:00 IST<br />Usual response: 24–48 business hours</span></div></div><form className="contact-form" onSubmit={submit}><label>Name<input name="name" required minLength={2} autoComplete="name" /></label><label>Email<input name="email" type="email" required autoComplete="email" /></label><label>Subject<select name="subject" required defaultValue=""><option value="" disabled>Select a topic</option><option>Account support</option><option>Reward or redemption</option><option>Affiliate enquiry</option><option>Privacy request</option><option>Business enquiry</option><option>Report abuse</option></select></label><label>Message<textarea name="message" required minLength={20} rows={6} /></label><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off" /></label><button className="button" type="submit">Prepare email <Send /></button>{status && <p className="form-status" role="status">{status}</p>}<small>This form prepares an email on your device. Future-X does not receive it until you send it.</small></form></section></main>;
}
