import PolicyPage from "../components/PolicyPage";
export default function Disclaimer() { return <PolicyPage title="Disclaimer" description="Important limits concerning Future-X entertainment, X-Coins, rewards, ads and third-party content." path="/disclaimer" sections={[
  { title: "No income, financial service or investment promise", content: <p>Future-X is an entertainment and engagement platform. It does not offer employment, a bank account, cryptocurrency, investment, savings product, money-transfer service or guaranteed earning opportunity. X-Coins are promotional platform points and are not money or income.</p> },
  { title: "No guaranteed rewards", content: <p>Displayed X-Coins, wallet balances, conversion estimates and reward options remain subject to the applicable rules, limits, verification, review and availability. Participation, past rewards or a pending request does not guarantee future credit, approval, payment or fulfilment.</p> },
  { title: "Games and Spin & Win", content: <p>Games and Spin &amp; Win are promotional entertainment features. Outcomes may vary, attempts may be limited and no prize is promised. Users should not treat these features as gambling or a way to make money.</p> },
  { title: "Ads, affiliates and external content", content: <p>Advertisements, affiliate offers, links and third-party content are controlled by independent providers. Their presence does not make Future-X the manufacturer, seller or guarantor. Review the provider’s terms, privacy policy, price and suitability before engaging.</p> },
  { title: "Information and availability", content: <p>General information is not financial, legal, medical or other professional advice. We work to keep Future-X accurate and available, but errors, delays, outages and outdated information may occur. To the extent permitted by law, the service is provided “as available”.</p> },
  { title: "Consumer rights", content: <p>Nothing in this disclaimer limits rights or liabilities that cannot be limited under applicable law.</p> },
]} />; }
