import Seo from "../components/Seo";

const faqs = [
  ["Account", "How do I create and verify an account?", "Follow the registration steps in the app and verify the mobile number with the one-time password sent through the authentication service. Keep your OTP private; Future-X support will never ask for it."],
  ["X-Coins", "What are X-Coins?", "X-Coins are revocable promotional platform points used to record eligible participation. They are not money, cryptocurrency, a bank balance, property, an investment, wages or guaranteed income."],
  ["Wallet", "Is the X-Coin wallet a financial account?", "No. It is an internal record of promotional X-Coin credits, adjustments and reward requests. It is not a bank account or stored-money wallet."],
  ["Rewards", "Are X-Coins or rewards guaranteed?", "No. Credit and redemption depend on the displayed activity rules, eligibility, successful completion, limits, verification, review and current availability."],
  ["Conversion", "What does X-Coin conversion mean?", "It means applying the current in-app conversion rule to determine eligibility for an available promotional reward. It does not turn X-Coins into legal tender and the rate or available options may change."],
  ["Redemption", "How do I request a withdrawal or reward?", "Use the in-app conversion or redemption flow after meeting the displayed balance and eligibility requirements. A request may require identity or account checks and admin approval where applicable."],
  ["Redemption", "Why is my request pending or rejected?", "Requests may be reviewed for eligibility, duplicate activity, fraud, technical errors, limits and reward availability. Submission does not guarantee approval or fulfilment. Contact support with your account ID and request reference if you need a review."],
  ["Games", "Do games always award X-Coins?", "No. Only activities that display an X-Coin offer may qualify, and their rules can include completion, attempt, daily, device, account or verification limits."],
  ["Spin & Win", "Is Spin & Win gambling?", "It is a promotional entertainment feature. Users do not wager money, no prize is promised, attempts may be limited and any X-Coin award remains subject to the displayed rules and review."],
  ["Tasks", "How do daily tasks and Play & Earn work?", "Each available task shows its completion and reward conditions. A task may expire, reach a limit or require verification before eligible X-Coins appear."],
  ["Reels", "What rules apply to short videos?", "Reels and any user or partner content must follow the Community Guidelines. Content may be reviewed, limited or removed for safety, legal or policy reasons."],
  ["Ads", "Why does Future-X show ads?", "Ads help support the service. Google AdMob may process advertising identifiers, device data, consent choices and ad interactions as explained in our Privacy Policy. Do not click or interact with ads artificially."],
  ["Affiliate", "Are affiliate offers required?", "No. They are optional third-party campaigns. Future-X may receive a commission from eligible actions. Review the provider’s price, privacy, billing, return and other terms before continuing."],
  ["Security", "What activity is prohibited?", "Bots, scripts, emulators, duplicate accounts, false details, OTP abuse, artificial ad engagement, manipulated spins or task completion and exploitation of errors are prohibited and may void X-Coins."],
  ["Privacy", "What data does Future-X use?", "Depending on the features used, Future-X processes account, OTP-verification status, device, activity, advertising, X-Coin, wallet, redemption, reward-history and support data. See the Privacy Policy for full details."],
  ["Delete account", "Can I delete my account and data?", "Yes. Use the in-app deletion control if shown, or email admin@future-x.co.in from your registered address. The Delete Account page explains verification, deleted data and limited retention."],
  ["Support", "How do I get help?", "Email admin@future-x.co.in with your account ID, activity or request name, date and non-sensitive evidence. Never send your password, OTP, full card number or banking password."],
];

export default function Faq() { const schema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([, q, a]) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } })) }; return <main id="main-content" className="page-main"><Seo title="Future-X Frequently Asked Questions" description="Answers about Future-X OTP accounts, reels, games, Spin & Win, tasks, AdMob, X-Coins, wallet, rewards and deletion." path="/faq" schema={schema} /><header className="page-hero compact"><div className="container narrow"><span className="eyebrow">Help centre</span><h1>Frequently asked questions</h1><p>Clear answers about features, data, fair participation and promotional rewards.</p></div></header><section className="section container narrow faq-list">{faqs.map(([category, question, answer]) => <details key={question}><summary><span>{category}</span>{question}</summary><p>{answer}</p></details>)}</section></main>; }
