import PolicyPage from "../components/PolicyPage";

export default function Privacy() { return <PolicyPage title="Privacy Policy" description="How Future-X collects, uses, shares and protects personal information." path="/privacy-policy" sections={[
  { title: "Scope", content: <p>This policy applies to the Future-X website, Android application and related support services. It should be read with our Terms and activity-specific notices.</p> },
  { title: "Information we collect", content: <><p>Depending on the features you use, we may collect:</p><ul><li>account data such as name, email address, mobile number and authentication identifier;</li><li>profile, eligibility and support information you provide;</li><li>activity records including games, lessons, surveys, tasks, referrals, X-Coins and redemption history;</li><li>device, app version, language, IP address, diagnostics and security events;</li><li>advertising identifiers and interaction data where ads or affiliate campaigns are enabled; and</li><li>purchase or redemption status. We do not ask you to send full card or banking credentials through support.</li></ul></> },
  { title: "How we use information", content: <ul><li>provide accounts, activities, X-Coins and eligible rewards;</li><li>authenticate users and prevent duplicate accounts, fraud and abuse;</li><li>operate support, respond to rights requests and communicate service notices;</li><li>measure reliability, fix errors and improve the platform;</li><li>administer optional advertising and affiliate campaigns; and</li><li>comply with law and enforce our policies.</li></ul> },
  { title: "Services and sharing", content: <><p>We may use service providers for authentication, hosting, analytics, advertising, communications, fraud prevention and support. These may include Google Firebase, Google Play services, Google AdMob, Google Cloud and Cloudflare where enabled in the product.</p><p>We may also share limited campaign information with an affiliate or survey provider when you choose its offer. Their own privacy terms apply. We do not sell personal information for cash.</p></> },
  { title: "Advertising and affiliate choices", content: <p>Ads or affiliate content may use device or interaction information subject to consent and device settings. You can reset or limit the Android advertising identifier through device settings. Affiliate offers are optional.</p> },
  { title: "Retention", content: <p>We keep information only for as long as reasonably needed for the purposes above, legal obligations, dispute handling and fraud prevention. Account data is scheduled for deletion after a verified request, except limited records that law or legitimate security needs require us to retain. Backup deletion may take additional time.</p> },
  { title: "Security", content: <p>We use administrative, technical and organisational safeguards appropriate to the information handled. No internet service is completely secure, so users should protect credentials and report suspected misuse promptly.</p> },
  { title: "Your choices and rights", content: <p>Subject to applicable law, you may request access, correction or deletion, object to certain uses, withdraw consent where processing relies on consent, or complain to the appropriate authority. Account deletion instructions are available on the Delete Account page.</p> },
  { title: "Children", content: <p>Future-X is not directed to children under 13. Users who have not reached the age of legal majority in their location require permission and supervision from a parent or legal guardian. Some activities or rewards may have a higher minimum age.</p> },
  { title: "Changes", content: <p>We may update this policy when features, providers or legal requirements change. The effective date will be updated and material changes may also be communicated in the app.</p> },
  { title: "Contact", content: <p>For privacy or data rights requests, email <a href="mailto:admin@future-x.co.in">admin@future-x.co.in</a> with the subject “Privacy Request”. We may verify your identity before acting.</p> },
]} />; }
