import PolicyPage from "../components/PolicyPage";

export default function Privacy() { return <PolicyPage title="Privacy Policy" description="How Future-X collects, uses, shares, retains and protects information across its website and Android app." path="/privacy-policy" sections={[
  { title: "Scope and controller", content: <p>This policy applies to the Future-X website, Android app, account, support and reward services. Future-X is responsible for the processing described here. Activity-specific notices and third-party privacy policies may also apply.</p> },
  { title: "Information we collect", content: <><p>Depending on how you use Future-X, we may collect:</p><ul><li>account and profile information, including your name, mobile number, email address, user ID and profile details;</li><li>mobile-number verification records, such as whether an OTP was successfully verified. OTP codes are used for authentication and should never be shared with support;</li><li>participation records for reels, games, Spin &amp; Win, Play &amp; Earn, daily tasks and affiliate campaigns;</li><li>X-Coin credits, adjustments, wallet balance, conversion requests, redemption or withdrawal status, reward history and review outcomes;</li><li>support messages, abuse reports and information you voluntarily provide;</li><li>device and technical data, including device type, operating system, app version, language, IP address, crash logs, diagnostics and security events; and</li><li>advertising identifiers, consent signals, ad impressions, clicks and related interaction data where AdMob or advertising features are enabled.</li></ul><p>Do not send passwords, OTP codes, full card numbers, banking passwords or other sensitive credentials to support.</p></> },
  { title: "Why and how we use information", content: <ul><li>create, authenticate and secure accounts, including mobile OTP verification;</li><li>deliver content, games, tasks, affiliate campaigns and advertising;</li><li>calculate, display and administer X-Coins, wallet balances, conversions, redemption requests and reward history;</li><li>verify completion and eligibility, apply admin-configured reward rules, correct errors and prevent fraud, bots, duplicate accounts or manipulation;</li><li>provide support, investigate reports and communicate service or policy notices;</li><li>monitor performance, diagnose errors and improve safety and reliability; and</li><li>comply with legal obligations and enforce our Terms and policies.</li></ul> },
  { title: "Firebase and service providers", content: <><p>Future-X uses Google Firebase services for functions such as authentication, database storage, hosting, diagnostics and user or reward tracking, depending on the app configuration. Firebase may process identifiers, device information, technical data and app activity on our behalf.</p><p>We may also use Google Play services, Google AdMob, hosting, communications, security, analytics and support providers. These providers process limited data to perform services for us under their own terms and applicable data-protection obligations.</p></> },
  { title: "Advertising and AdMob", content: <p>The app may display Google AdMob ads. Google and its partners may process advertising identifiers, device information, approximate location inferred from IP address, consent choices and ad interaction data to deliver, measure and protect ads. Personalised ads are used only where permitted and subject to required consent. You can manage ad privacy choices through the app where offered and Android or Google settings.</p> },
  { title: "Affiliate campaigns and external services", content: <p>Affiliate campaigns are optional. When you open an affiliate link, a campaign identifier and limited interaction data may be shared with the relevant network or provider so that an eligible action can be attributed. If you transact with that provider, it independently controls the information you submit to it. Review its privacy policy before continuing.</p> },
  { title: "When information may be shared", content: <p>We may share information with the processors described above; with an affiliate or reward provider when needed to verify an action or fulfil an eligible redemption; with professional advisers; when required by law or valid legal process; or when reasonably necessary to protect users, rights and platform security. We do not sell personal information for money.</p> },
  { title: "Retention", content: <p>We retain information only as long as reasonably necessary to provide the service, keep accurate reward and security records, resolve disputes, prevent repeat abuse and meet legal obligations. Retention periods vary by record. After a verified deletion request, eligible account data is deleted or de-identified; limited fraud-prevention, transaction, legal or security records may be retained where necessary. Residual backup copies may take up to 90 days to expire.</p> },
  { title: "Security", content: <p>We use reasonable administrative, technical and organisational measures, including access controls and secure transport. No online service is completely secure. Protect your device and OTPs, and report suspected unauthorised access promptly.</p> },
  { title: "Your choices and rights", content: <p>Subject to applicable law, you may request access, correction or deletion of personal information, withdraw consent where processing relies on consent, object to certain processing, or complain to the appropriate authority. You can request account deletion through the app or the Delete Account page. We may verify identity before fulfilling a request.</p> },
  { title: "Children and age requirements", content: <p>Future-X is not directed to children under 13. A person below the age of legal majority in their location may use the service only with permission and supervision from a parent or legal guardian. Particular ads, campaigns, games or reward options may require a higher age. We may restrict or close an account that does not meet applicable requirements.</p> },
  { title: "International processing and changes", content: <p>Service providers may process information outside your state or country, subject to applicable safeguards. We may update this policy as features, providers or legal requirements change. Material changes will be communicated where required.</p> },
  { title: "Contact", content: <p>For privacy questions or rights requests, email <a href="mailto:admin@future-x.co.in?subject=Privacy%20Request">admin@future-x.co.in</a> with the subject “Privacy Request”.</p> },
]} />; }
