import PolicyPage from "../components/PolicyPage";
export default function RefundPolicy() { return <PolicyPage title="Refund Policy" description="Refund and reversal information for Future-X promotional rewards and third-party transactions." path="/refund-policy" sections={[
  { title: "No purchase of X-Coins", content: <p>Future-X does not sell X-Coins through this website. X-Coins are promotional platform points, not purchased currency, so unused, expired, corrected or reversed X-Coins are not eligible for a cash refund.</p> },
  { title: "Reward and redemption requests", content: <p>An X-Coin conversion, withdrawal or redemption is a request for an available promotional reward. It is not a refund and is not guaranteed. A pending request may be reviewed, delayed, rejected or reversed under the Responsible Rewards Policy. Once a digital or other reward has been successfully fulfilled to the details supplied by the user, it may be non-cancellable and non-refundable unless applicable law or the fulfilment provider requires otherwise.</p> },
  { title: "Affiliate and third-party purchases", content: <p>A purchase made after following an affiliate link is a transaction with the named third-party seller, not Future-X. The seller controls billing, cancellation, return and refund decisions. Contact it using your order confirmation and review its policy. Reversing or refunding a qualifying purchase may also make related X-Coins ineligible.</p> },
  { title: "Advertising", content: <p>Viewing or interacting with an advertisement does not create a purchase from Future-X. Questions about an advertised product or charge must be directed to the advertiser or seller shown in the transaction.</p> },
  { title: "Unrecognised charges and errors", content: <p>If a charge specifically identifies Future-X and you do not recognise it, email <a href="mailto:admin@future-x.co.in?subject=Charge%20Enquiry">admin@future-x.co.in</a> promptly with the date, amount and a masked or non-sensitive transaction reference. Never send full card details, banking passwords or OTPs.</p> },
  { title: "Future paid services", content: <p>If Future-X introduces a paid service, the price, billing entity, cancellation process and applicable refund rights will be displayed before purchase, and this policy will be updated.</p> },
]} />; }
