import PolicyPage from "../components/PolicyPage";
export default function ResponsibleRewards() { return <PolicyPage title="Responsible Rewards & Fair Use Policy" description="Rules for fair participation, promotional X-Coin credit, conversion and eligible reward redemption." path="/responsible-rewards" sections={[
  { title: "What X-Coins are", content: <p>X-Coins are revocable promotional points that record eligible participation inside Future-X. They are not money, cryptocurrency, a bank balance, property, wages, an investment or guaranteed income. They have no value outside an eligible reward option currently offered by Future-X.</p> },
  { title: "How X-Coins may be awarded", content: <p>Eligible games, Spin &amp; Win attempts, Play &amp; Earn activities, daily tasks, short-video activities or affiliate campaigns may offer X-Coins under rules shown in the app. Amounts are controlled by current platform configuration and may vary. Opening an activity or seeing an estimated amount does not itself create an entitlement.</p> },
  { title: "Completion and limits", content: <p>Credit may depend on full completion, time windows, attempt or daily limits, location, device, account standing, advertiser or partner confirmation and automated or manual verification. Delayed partner reporting may delay credit. Rewards are not guaranteed.</p> },
  { title: "Wallet and reward history", content: <p>The wallet and reward history are internal records of promotional points and requests. They are not financial statements. Pending, reversed, expired and approved entries may be displayed separately. Contact support if an entry appears incorrect; screenshots alone do not establish eligibility.</p> },
  { title: "Conversion and redemption", content: <p>Available conversion, withdrawal or redeem options may require a minimum balance, maximum amount, verified mobile number, accurate fulfilment details, waiting period, location eligibility, account review and admin approval. Conversion rates, inventory and options may change. A submitted or pending request is not a guaranteed reward or payment.</p> },
  { title: "Fraud and abuse prevention", content: <p>Bots, scripts, emulators, modified apps, repeat installations, duplicate accounts, false details, collusion, fabricated completion, artificial ad interactions and exploitation of errors are prohibited. We may pause review, reverse affected X-Coins, reject requests, restrict features or close accounts. Technical mistakes may be corrected even after points appear.</p> },
  { title: "Affiliate campaigns and ads", content: <p>Affiliate offers are optional and third-party terms apply. Never buy something solely to chase X-Coins. Ad rewards, where offered, require genuine eligible viewing; clicking ads or interacting with them artificially is prohibited. No purchase or ad click guarantees a reward.</p> },
  { title: "Healthy participation", content: <p>Take breaks and set reasonable time limits. Do not spend money or time you cannot afford to lose. Future-X is optional entertainment and engagement, not employment or a livelihood. If participation becomes stressful or compulsive, stop using the feature and seek appropriate support.</p> },
  { title: "Questions and reviews", content: <p>For a reward review, email <a href="mailto:admin@future-x.co.in?subject=Reward%20Review">admin@future-x.co.in</a> with your account ID, activity name, date and non-sensitive evidence. Never send an OTP or password.</p> },
]} />; }
