import PolicyPage from "../components/PolicyPage";

export default function Terms() { return <PolicyPage title="Terms & Conditions" description="Rules for Future-X accounts, content, games, tasks, affiliate campaigns, X-Coins and reward redemption." path="/terms-and-conditions" sections={[
  { title: "Acceptance", content: <p>By accessing Future-X, you agree to these Terms, our Privacy Policy, Responsible Rewards Policy, Community Guidelines and any rules displayed for a specific activity. If you do not agree, do not use the service.</p> },
  { title: "Eligibility and account security", content: <><p>You must meet the age, location and other requirements shown for the service and each activity, provide accurate information, and use only an account you are authorised to control. A minor must have permission and supervision from a parent or legal guardian where required.</p><p>You are responsible for securing your device and account. Never share an OTP. Unless Future-X gives written permission, each person may maintain only one account and each mobile number may be subject to account limits.</p></> },
  { title: "Platform features", content: <p>Available features may include reels or short videos, games, Spin &amp; Win, Play &amp; Earn activities, daily tasks, affiliate campaigns, ads, profiles, wallet views, reward history and X-Coin redemption. Features and availability may differ by account, device, version, age, location or campaign and may change or end.</p> },
  { title: "X-Coins", content: <><p>X-Coins are revocable promotional platform points used to record eligible participation. They are not money, legal tender, cryptocurrency, a bank deposit, a security, property, wages, an investment or guaranteed income. A wallet balance is only an internal record of X-Coins and is not a financial account.</p><p>X-Coin amounts are determined by current, admin-configured activity rules. Displayed amounts may be subject to completion, limits and verification. We may correct technical or administrative errors and reverse duplicate, ineligible, fraudulent or improperly credited points.</p></> },
  { title: "Conversion, redemption and withdrawal requests", content: <><p>Where the app offers an X-Coin conversion, redeem or withdrawal flow, it is a request for an available promotional reward—not a transfer from a bank account. Options may have minimum balances, maximum amounts, frequency limits, verification requirements, service areas, processing times and provider availability.</p><p>Requests may require manual or automated review and, where applicable, admin approval. Submission does not guarantee approval, payment or fulfilment. Pending requests may be declined, delayed or cancelled for failed eligibility, inaccurate details, suspected abuse, technical error, legal restrictions or unavailable reward inventory. Current in-app terms control each option.</p></> },
  { title: "Games, Spin & Win and chance-based presentation", content: <p>Games and Spin &amp; Win are promotional entertainment features. Users do not wager money or purchase X-Coins to participate unless a separate lawful offer expressly states otherwise. Outcomes, attempts, limits and any promotional X-Coin awards are governed by the displayed rules. Participation is not gambling, does not promise a prize and must not be treated as a way to earn a living.</p> },
  { title: "Ads, affiliate campaigns and third parties", content: <p>The app may show AdMob ads and optional affiliate offers. Future-X may receive advertising revenue or a commission for an eligible third-party action. No purchase is required to use core features. Independent providers control their products, prices, billing, privacy practices, fulfilment, warranties and refunds. Their terms apply when you leave Future-X.</p> },
  { title: "User content and conduct", content: <p>If reels, profiles or other features allow content or interaction, you retain responsibility for what you submit and grant Future-X the limited rights needed to host, display, moderate and operate it. You must have all necessary rights and must follow the Community Guidelines.</p> },
  { title: "Prohibited conduct", content: <ul><li>bots, scripts, automation, emulators, modified clients or other manipulation of activities, ads, games, spins, tasks or reward tracking;</li><li>duplicate accounts, false identity or eligibility data, OTP abuse, collusion or unauthorised account access;</li><li>click fraud, artificial ad engagement or conduct that violates an advertiser’s or affiliate provider’s rules;</li><li>selling or transferring accounts or X-Coins, or falsely claiming rewards are guaranteed;</li><li>unlawful, harmful, deceptive, abusive or infringing content; or</li><li>interference with security, Firebase records, code, networks or service availability.</li></ul> },
  { title: "Review, suspension and termination", content: <p>We may review activity, withhold or reverse X-Coins, remove content, limit features, reject a redemption, suspend or close an account when reasonably necessary to correct an error, investigate suspected abuse, protect users, comply with law or enforce these Terms. You may contact support to request review, but outcomes are not guaranteed.</p> },
  { title: "Availability and changes", content: <p>We may change or discontinue features, reward rates, limits, conversion ratios and reward options. Rewards and continuous service availability are not guaranteed. Where required, material changes will be communicated before they take effect.</p> },
  { title: "Disclaimers and liability", content: <p>To the extent permitted by law, Future-X is provided “as available” without a promise of uninterrupted access, income, a particular X-Coin amount, redemption outcome or third-party result. Future-X is not liable for independent third-party products or conduct. Nothing here excludes liability or consumer rights that cannot lawfully be excluded.</p> },
  { title: "Governing law and contact", content: <p>These Terms are governed by the laws of India. Courts with appropriate jurisdiction in Uttar Pradesh will handle disputes, subject to mandatory consumer rights. Questions may be sent to <a href="mailto:admin@future-x.co.in">admin@future-x.co.in</a>.</p> },
]} />; }
