import PolicyPage from "../components/PolicyPage";

export default function Terms() { return <PolicyPage title="Terms & Conditions" description="The rules for using Future-X accounts, activities, X-Coins and eligible rewards." path="/terms-and-conditions" sections={[
  { title: "Acceptance", content: <p>By using Future-X, you agree to these Terms, our Privacy Policy and the rules displayed for each activity. If you do not agree, do not use the service.</p> },
  { title: "Eligibility and accounts", content: <><p>You must provide accurate information, meet applicable age and location requirements and keep your account secure. One person may not operate multiple accounts unless Future-X gives written permission.</p><p>You are responsible for activity on your account. Contact support promptly if you suspect unauthorised access.</p></> },
  { title: "Activities", content: <p>Games, learning modules, surveys, reward tasks, referrals and affiliate campaigns may have separate eligibility, completion, timing and availability rules. Availability can vary by user, device or location. Participation does not guarantee X-Coins or any reward.</p> },
  { title: "X-Coins and rewards", content: <><p>X-Coins are promotional platform points. They are not legal tender, cryptocurrency, a bank deposit, property, an investment or guaranteed income. X-Coins have no value outside Future-X except through an eligible reward option we make available.</p><p>Credits and redemptions may be subject to verification, limits, expiry, availability and fraud review. We may correct errors or reverse points obtained through abuse, duplication or failed eligibility.</p></> },
  { title: "Affiliate and third-party services", content: <p>Optional affiliate, advertising, survey or other third-party content is provided by independent parties. Future-X may receive a commission from eligible transactions. Third-party terms, privacy practices, warranties and return policies apply.</p> },
  { title: "Prohibited conduct", content: <ul><li>fraud, automation, emulators or manipulation used to obtain rewards;</li><li>duplicate, false or purchased accounts;</li><li>harassment, unlawful content or infringement of others' rights;</li><li>interference with security, code, networks or activity tracking; and</li><li>selling accounts, X-Coins or access without written permission.</li></ul> },
  { title: "Suspension and termination", content: <p>We may restrict, suspend or close an account when reasonably necessary to investigate abuse, protect users, comply with law or enforce these Terms. Where appropriate, users may contact support to request review.</p> },
  { title: "Availability and changes", content: <p>Features, rates, limits and reward options may change. We do not promise uninterrupted or error-free availability. Material changes will be communicated where required.</p> },
  { title: "Disclaimers and liability", content: <p>Future-X is provided on an “as available” basis to the extent permitted by law. We do not guarantee earnings, specific rewards or third-party products. Nothing in these Terms excludes rights or liabilities that cannot legally be excluded.</p> },
  { title: "Governing law", content: <p>These Terms are governed by the laws of India. Courts with appropriate jurisdiction in Uttar Pradesh will handle disputes, subject to mandatory consumer rights.</p> },
  { title: "Contact", content: <p>Questions may be sent to <a href="mailto:admin@future-x.co.in">admin@future-x.co.in</a>.</p> },
]} />; }
